version: '3.4'
services:
  userinterface:
    image: redditorui
    restart: always
    volumes:
      - ./.env:/usr/src/app/.env
      - ./redditor-ui/public:/usr/src/app/public
      - ./redditor-ui/src:/usr/src/app/src
    environment:
      - REACT_APP_HOST=${REACT_APP_HOST}
    ports:
      - "3000:3000"
  redditapi:
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8000:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron
  redditapitwo:
    image: redditorapi
    command: /app/plumber.R
    restart: always
    ports:
     - "8001:8000"
    working_dir: /app
    volumes:
      - ./.env:/app/.Renviron

volumes:
  mongodbdata:
  postgres: {}
  redditor_data: {}
  airflow-worker-logs:
